### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by Jalle19** [Jalle19/pvr.vbox#10]

**Comment by pauldmallett** [comment]
Hi
Sorry to jump in here but I'm floundering about with your pvr.vbov, it's my first shot at cmake; we all have to start somewhere so be kind.
Ran cmake and got this...........
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "Findkodi.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "kodi", but
  CMake did not find one.

  Could not find a package configuration file provided by "kodi" with any of
  the following names:

    kodiConfig.cmake
    kodi-config.cmake
--------------------------------------------------------------------------------------------------------------------
Installed Kodi on Lubuntu 14.04 with apt-get so do I need to reinstall from source or can I edit:
CMakeList.txt................
find_package(kodi REQUIRED)
find_package(kodiplatform REQUIRED)
find_package(TinyXML2 REQUIRED)

include_directories(${kodiplatform_INCLUDE_DIRS}
                    ${KODI_INCLUDE_DIR}
                    ${TINYXML2_INCLUDE_DIRS})
To find Kodi.....................
/usr/bin/kodi, /usr/lib/kodi, /usr/bin/X11/kodi, /usr/share/kodi, /usr/share/man/man1/kodi.1.gz

It's all inside VirtualBox so no worries.

**Comment by Jalle19** [comment]
You'll need the Kodi sources in order to build the addon, I'll post instructions as soon as I get around to.

**Comment by Jalle19** [comment]
I've added build instructions for Windows and included a link to the Kodi forums where they have general instructions for other platforms as well.
