### ISSUE TITLE
Kodi/PVR Manager freeze when loading channels pvr.vbox

### ISSUE THREAD

**Issue by dhead666** [Jalle19/pvr.vbox#12]
Seems like tinyxml2 is crashing, I've tried notspiff'2 1.0.12, leethomason's 2.2.0 & 3.0.0.

Not much info in the logs.

Using [kodi b9a9083bd9757f375879999ce0638d5f10b871a9](https://github.com/xbmc/kodi-platform/tree/b9a9083bd9757f375879999ce0638d5f10b871a9 )

http://sprunge.us/IKfU

```
Starting program: /usr/lib/kodi/kodi.bin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
sh: lsb_release: command not found
[New Thread 0x7fffdf73b700 (LWP 19099)]
[New Thread 0x7fffdff3c700 (LWP 19098)]
[New Thread 0x7fffdbf3b700 (LWP 19097)]
[New Thread 0x7fffc7ffe700 (LWP 19105)]
[New Thread 0x7fff8ffff700 (LWP 19119)]
[New Thread 0x7fffc57f9700 (LWP 19110)]
[New Thread 0x7fffc4ff8700 (LWP 19111)]
[New Thread 0x7fff8cfe9700 (LWP 19124)]
[New Thread 0x7fff9dffb700 (LWP 19116)]
[Thread 0x7fff8cfe9700 (LWP 19124) exited]
[New Thread 0x7fffc6ffc700 (LWP 19107)]
[New Thread 0x7fff9f7fe700 (LWP 19113)]
[Thread 0x7fffc57f9700 (LWP 19110) exited]
[New Thread 0x7fff8956a700 (LWP 19128)]
[New Thread 0x7fff8768e700 (LWP 19127)]
[New Thread 0x7ffff7f2a700 (LWP 19123)]
[New Thread 0x7fff8dbf3700 (LWP 19122)]
[New Thread 0x7fff8e3f4700 (LWP 19121)]
[New Thread 0x7fff8ebf5700 (LWP 19120)]
[New Thread 0x7fff9cff9700 (LWP 19118)]
[New Thread 0x7fff9d7fa700 (LWP 19117)]
[New Thread 0x7fff9e7fc700 (LWP 19115)]
[New Thread 0x7fff9effd700 (LWP 19114)]
[New Thread 0x7fff9ffff700 (LWP 19112)]
[New Thread 0x7fffc5ffa700 (LWP 19109)]
[New Thread 0x7fffc67fb700 (LWP 19108)]
[New Thread 0x7fffc77fd700 (LWP 19106)]
[New Thread 0x7fffdd88d700 (LWP 19102)]
[New Thread 0x7fffde08e700 (LWP 19101)]
[New Thread 0x7fffde88f700 (LWP 19100)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8956a700 (LWP 19128)]
0x00007fff9c3876b3 in tinyxml2::XMLElement::QueryUnsignedText(unsigned int*) const () from /usr/lib/libtinyxml2.so.1
```

**Comment by Jalle19** [comment]
Can you get the full backtrace?

**Comment by dhead666** [comment]
'''
#0  0x00007fff9e3c66b3 in tinyxml2::XMLElement::QueryUnsignedText(unsigned int*) const () from /usr/lib/libtinyxml2.so.1
No symbol table info available.
#1  0x00007fff9e5eea25 in vbox::response::RecordingResponseContent::CreateRecording(tinyxml2::XMLElement const*) const () from /usr/lib/kodi/addons/pvr.vbox/pvr.vbox.so
No symbol table info available.
#2  0x00007fff9e5ef64a in vbox::response::RecordingResponseContent::GetRecordings() const () from /usr/lib/kodi/addons/pvr.vbox/pvr.vbox.so
No symbol table info available.
#3  0x00007fff9e5e4dbb in vbox::VBox::RetrieveRecordings() () from /usr/lib/kodi/addons/pvr.vbox/pvr.vbox.so
No symbol table info available.
#4  0x00007fff9e5e8976 in ?? () from /usr/lib/kodi/addons/pvr.vbox/pvr.vbox.so
No symbol table info available.
#5  0x00007ffff0c35df0 in execute_native_thread_routine () from /usr/lib/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff67a4374 in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#7  0x00007ffff06aa27d in clone () from /usr/lib/libc.so.6
No symbol table info available.
'''

**Comment by Jalle19** [comment]
Thanks, I'll look into it - I think I know what the problem is.
