### ISSUE TITLE
pre 2.47.x recordings cannot be deleted

### ISSUE THREAD

**Issue by dhead666** [Jalle19/pvr.vbox#24]
old recordings that made on fw preceding 2.47.x are listed in kodi but cannot be deleted.

**Comment by Jalle19** [comment]
I think the only solution here is to ignore recordings that don't have a record-id. If the firmware is updated in the future to contain it they will start appearing again.

**Comment by dhead666** [comment]
Agree as users will complain that there's a bug in the addon if they can't delete these recordings, so these recording should not be visible, that's is unless a notification can appear when a user tries to delete such recording which will inform that due to changes in fw it can only be deleted through the LiveTV web app.

**Comment by Jalle19** [comment]
Unfortunately it's not possible to display a popup from an addon, the best I could do is display one of those small notification boxes that show up in the lower right of the screen. They disappear very quickly though so they're not very helpful for these kind of notifications.
