### ISSUE TITLE
epg window: program recording status isn't updated

### ISSUE THREAD

**Issue by dhead666** [Jalle19/pvr.vbox#25]
when adding a recording the program status isn't changing in the epg window and the program info window, at least for a running program.

steps to reproduce:
* open the epg window
* choose a program (at least a currently running one)
* press the record button

also see screensnap attached
https://i.imgur.com/qaM1BKp.png

**Comment by Jalle19** [comment]
Part of this seems to be a bug in the firmware, if you start recording a currently running program it will add a timer in scheduled state instead of starting the recording immediately. I believe this is a regression in recent firmwares since it used to work.

**Comment by Jalle19** [comment]
@dhead666 can you try rescanning the EPG on your device? I think mine at least has gotten dumb after the switch to summer time.

**Comment by dhead666** [comment]
Rescanned EPG, cleaned PVR DB, Kodi and VBox device clocks synced.

Not sure what's going on, getting segfault on EPG window, GDB: http://sprunge.us/OaEY , Kodi log: http://sprunge.us/jSJF

EPG OSD for the video now playing window shows only two programs for each channel, the current running program and the previous,

**Comment by Jalle19** [comment]
Can you check if the VBox has any guide data at all? I have a feeling the crash is unrelates, it's alpha software after all.

**Comment by dhead666** [comment]
Sorry for the late answer, I've looked at this again and at first just after initiating an epg rescan the guide in kodi does represent the limited entries that available on the device.

The problem is that just after the device has a more extended epg (confirmed against the xml on the device and the livetv web app), kodi still has the same limited values as before (even if I reset the pvr db), kodi gets the extended updated epg a bit later (like 5~15 min, at least when I force pvr db reset).

**Comment by Jalle19** [comment]
This issue should have been fixed recently, now when you start recording something from the EPG timeline view the item gets a recording icon to indicate that it is recording. Older recordings that are still visible in the timeline also get a small "play" icon which can be used to play the completed recording.
