### ISSUE TITLE
std::put_time only available for gcc >= 5.0

### ISSUE THREAD

**Issue by dhead666** [Jalle19/pvr.vbox#6]
Failing to build with gcc 4.9.2 as std::put_time which used in https://github.com/Jalle19/pvr.vbox/blob/master/src/vbox/xmltv/Utilities.h#L68 is missing, it was only added in gcc 5.0 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54354

**Comment by Jalle19** [comment]
I've fixed this locally, will probably push later tonight along with external XMLTV support.

**Comment by dhead666** [comment]
Great, I'll time tonight to test it on Linux.
